foxyblue/foolscap

foolscap.py
src/note_utils.py
src/parse_utils.py

Allows foolscap to create a new note from the command line
and write it to storage.

Create new note functionality

---

foolscap.py
src/note_utils.py
src/parse_utils.py

foolscap now has the ability to move lines across notes.

Implement move lines feature

---

foolscap/note_content.py
foolscap/note_data.py
foolscap/parse_text.py

Make paths cross os compatible

---

foolscap/actor.py
foolscap/cli.py
foolscap/file_paths.py
foolscap/meta_data.py
foolscap/migrate_data.py
foolscap/parse_text.py
tests/test_parse_text.py

Implement data migration, datetime (meta) and views

---

foolscap/migrate_data.py

- forgot to save the data after migrating

Fix migration mix

---

foolscap/note_display.py
tests/data/test_meta_data.py
tests/test_note_display.py

Resolves #46 Create Custom Sort
Resolves #42 Do not open display if tag does not exist

Implement custom sort of notes, incl. tests

---

.travis.yml
requirements.txt
setup.py
tox.ini

resolves #57 implement coverage reports for unit tests.

Implement test coverage reporting

---

foolscap/migrate_data.py

Fix typo - create, remove timestamp from meta_data

---

foolscap/note_content.py
foolscap/parse_text.py
tests/test_parse_text.py

Fix missing meta data

---

tests/test_parse_text.py

add tests for parse_text.edit_text

Improve test coverage

---

foolscap/parse_text.py
tests/test_parse_text.py

remove spaces - Resolves #45 
limit number of characters - Resolves #36

Add title restrictions

---

foolscap/file_paths.py
tox.ini

Change storage to an Env Var

---

foolscap/parse_text.py
tests/test_parse_text.py

Implement parsing of note sub headings

---

foolscap/display/console.py
foolscap/display/content_display.py
foolscap/display/key_events.py
foolscap/display/render_screen.py
foolscap/display/root_widget.py
tests/test_display/test_console.py
tests/test_display/test_content_display.py
tests/test_display/test_key_events.py
tests/test_display/test_render_screen.py
tests/test_display/test_root_widget.py

Refactor display to OOP structure

---

foolscap/display/key_events.py
tests/test_display/test_key_events.py

Allow not to loop on menu

---

foolscap/display/console.py
foolscap/display/content_display.py
foolscap/display/key_events.py
foolscap/note_display.py
foolscap/parse_text.py
tests/test_display/test_console.py
tests/test_display/test_content_display.py
tests/test_display/test_key_events.py

Implements scrolling in List mode.
Resolves #90 
Resolves #62

Implement list scrolling

---

foolscap/display/content_display.py

Fix bug with final note on screen

---

foolscap/note_content.py

Add print statements for operations

---

foolscap/display/render_screen.py
tests/test_display/test_render_screen.py

Display current path

---

foolscap/actor.py
foolscap/cli.py
foolscap/note_content.py
tests/test_actor.py

Implement note exporting to active directory

---

foolscap/parse_text.py
tests/test_parse_text.py

Ensure note titles are lowercase

---

foolscap/note_content.py
foolscap/parse_text.py
tests/data/test_note.txt
tests/test_parse_text.py

Add restrictions to new note titles

---

foolscap/note_content.py

Fix note name not being printed

---

foolscap/display/console.py
foolscap/display/content_display.py
foolscap/note_display.py
tests/data/mock_meta_data.py
tests/test_display/test_console.py
tests/test_display/test_content_display.py
tests/test_note_display.py

Pass sub heading to display and add indication

---

foolscap/actor.py
foolscap/cli.py
foolscap/note_display.py
tests/test_actor.py
tests/test_cli.py
tests/test_note_display.py

A new way to view notes in the menu

Add tag list type

---

scripts/patch_notes.py

Rudimentary Patch Note Creator

Add patch note script

---

foolscap/meta_data/io.py
foolscap/meta_data/parse_note.py
foolscap/note_display.py
tests/test_meta_data/test_common.py
tests/test_meta_data/test_parse_note.py

Subsections now included in meta data.

Index subsections

---

foolscap/actor.py
foolscap/display/content.py
foolscap/display/key_listener.py
foolscap/meta_data/__init__.py
foolscap/meta_data/io.py
foolscap/meta_data/models.py
foolscap/meta_data/utils.py
foolscap/note_display.py
tests/test_actor.py
tests/test_meta_data/mock_meta_data.py
tests/test_meta_data/test_models.py
tests/test_note_display.py
tox.ini

Implement MVC refactor

---

foolscap/file_paths.py
tox.ini

Change en var name from FSCAP_PATH to __FSCAP_DIR__

---

foolscap/meta_data/io.py
tests/test_meta_data/mock_meta_data.py
tests/test_meta_data/test_io.py

Create tests for data migration

---

foolscap/actor.py

Add socket binding to interrupt two instances opening

---

scripts/patch_notes.py

Also include doc-strings on the functions

Handle ENH and FEA together

---

foolscap/display/key_listener.py
foolscap/display/key_objects.py
foolscap/note_display.py
tests/test_display/test_key_objects.py

Ensure foolscap doesn't scroll when note count < 4

---

foolscap/display/menu_objects.py

Change the default column setting for length
